// Auto-generated by parallel_unsplash_photos_search
// Do not edit manually

import corporateHero from './generated/corporate_hero.png';
import globalNetwork from './generated/global_network.png';
import dashboardHero from './generated/dashboard_hero.png';
import sketchHero from './generated/sketch_hero_ai.png';
import sketchBusiness from './generated/sketch_business_collage.png';
import sketchGlobal from './generated/sketch_global_map.png';
import dataViz from './generated/data_viz.png';
import riskTech from './generated/risk_tech.png';

export const IMAGES = {
  COMPLIANCE_1: "https://images.unsplash.com/photo-1589935447067-5531094415d1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwxMHx8Y29tcGxpYW5jZSUyMG1vbml0b3Jpbmd8ZW58MHwwfHx8MTc2OTgxNTc1MHww&ixlib=rb-4.1.0&q=80&w=1080",
  COMPLIANCE_10: "https://images.unsplash.com/photo-1710547281729-b8ad6a6f5d06?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw1fHxjb21wbGlhbmNlJTIwbW9uaXRvcmluZ3xlbnwwfDB8fHwxNzY5ODE1NzUwfDA&ixlib=rb-4.1.0&q=80&w=1080",
  COMPLIANCE_2: "https://images.unsplash.com/photo-1584931421154-2bf69492aa2c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw2fHxjb21wbGlhbmNlJTIwbW9uaXRvcmluZ3xlbnwwfDB8fHwxNzY5ODE1NzUwfDA&ixlib=rb-4.1.0&q=80&w=1080",
  COMPLIANCE_3: "https://images.unsplash.com/photo-1609234153285-78b715b9dfd7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwzfHxjb21wbGlhbmNlJTIwbW9uaXRvcmluZ3xlbnwwfDB8fHwxNzY5ODE1NzUwfDA&ixlib=rb-4.1.0&q=80&w=1080",
  COMPLIANCE_4: "https://images.unsplash.com/photo-1696781016058-20913bc838db?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwyfHxjb21wbGlhbmNlJTIwbW9uaXRvcmluZ3xlbnwwfDB8fHwxNzY5ODE1NzUwfDA&ixlib=rb-4.1.0&q=80&w=1080",
  COMPLIANCE_5: "https://images.unsplash.com/photo-1621874250030-554a558f0db6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw4fHxjb21wbGlhbmNlJTIwbW9uaXRvcmluZ3xlbnwwfDB8fHwxNzY5ODE1NzUwfDA&ixlib=rb-4.1.0&q=80&w=1080",
  COMPLIANCE_6: "https://images.unsplash.com/photo-1667396473517-19461ee8eb4b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw3fHxjb21wbGlhbmNlJTIwbW9uaXRvcmluZ3xlbnwwfDB8fHwxNzY5ODE1NzUwfDA&ixlib=rb-4.1.0&q=80&w=1080",
  COMPLIANCE_7: "https://images.unsplash.com/photo-1689969599825-40b9a4e6cecc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwxfHxjb21wbGlhbmNlJTIwbW9uaXRvcmluZ3xlbnwwfDB8fHwxNzY5ODE1NzUwfDA&ixlib=rb-4.1.0&q=80&w=1080",
  COMPLIANCE_8: "https://images.unsplash.com/photo-1745867817232-9d92c805f6d2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw0fHxjb21wbGlhbmNlJTIwbW9uaXRvcmluZ3xlbnwwfDB8fHwxNzY5ODE1NzUwfDA&ixlib=rb-4.1.0&q=80&w=1080",
  COMPLIANCE_9: "https://images.unsplash.com/photo-1669988021067-624c6b1699ca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHw5fHxjb21wbGlhbmNlJTIwbW9uaXRvcmluZ3xlbnwwfDB8fHwxNzY5ODE1NzUwfDA&ixlib=rb-4.1.0&q=80&w=1080",
  CORPORATE_HERO: corporateHero,
  GLOBAL_NETWORK: globalNetwork,
  SKETCH_HERO: sketchHero,
  SKETCH_BUSINESS: sketchBusiness,
  SKETCH_GLOBAL: sketchGlobal,
  DASHBOARD_HERO_1: dashboardHero,
  DASHBOARD_HERO_10: dashboardHero,
  DASHBOARD_HERO_2: dashboardHero,
  DASHBOARD_HERO_3: dashboardHero,
  DASHBOARD_HERO_4: dashboardHero,
  DASHBOARD_HERO_5: dashboardHero,
  DASHBOARD_HERO_6: dashboardHero,
  DASHBOARD_HERO_7: dashboardHero,
  DASHBOARD_HERO_8: dashboardHero,
  DASHBOARD_HERO_9: dashboardHero,
  DATA_VIZ_1: dataViz,
  DATA_VIZ_10: dataViz,
  DATA_VIZ_2: dataViz,
  DATA_VIZ_3: dataViz,
  DATA_VIZ_4: dataViz,
  DATA_VIZ_5: dataViz,
  DATA_VIZ_6: dataViz,
  DATA_VIZ_7: dataViz,
  DATA_VIZ_8: dataViz,
  DATA_VIZ_9: dataViz,
  RISK_TECH_1: riskTech,
  RISK_TECH_2: riskTech,
  RISK_TECH_3: riskTech,
  RISK_TECH_4: riskTech,
  RISK_TECH_5: riskTech,
  RISK_TECH_6: riskTech,
} as const;

export type ImageKey = keyof typeof IMAGES;
